### PR TITLE
Adding XCM_reserve for KSM in Moonriver, Karura, Kinstugi, Heiko

### PR DESCRIPTION
**Pull request by stepanLav**
This PR adds:

- [Karura < KSM > Moonriver](https://github.com/nova-wallet/nova-utils/pull/608/commits/cce9dc4aaeebe37991e3dbd785cfdd88a2a175c0)
- [Moonriver < KSM > Kintsugi](https://github.com/nova-wallet/nova-utils/pull/608/commits/3200b4ef8dbe0565eba8605a2db804e3bbd32cfb)
- [Moonriver < KSM > Parallel Heiko](https://github.com/nova-wallet/nova-utils/pull/608/commits/44e4a1cd78675380f28e2e181f4bef0ea8fa17e0)
- [Karura < KSM > Parallel Heiko](https://github.com/nova-wallet/nova-utils/pull/608/commits/c14d96bf88cc0af6291025e47bcd70401e0c5ee5)
- [Parallel Heiko < KSM > Kintsugi](https://github.com/nova-wallet/nova-utils/pull/608/commits/bacb76840739594714f48ced831eab77d63b6e9c)
- [Karura < KSM > Kintsugi](https://github.com/nova-wallet/nova-utils/pull/608/commits/9c9cfb2ee5ee80e57209e65045c4944ef47edd79)

### CODE REVIEW

**Comment by stepanLav** [comment]
KSM Karura -> Moonriver ❌
Extrinsic: https://karura.subscan.io/extrinsic/2309993-2

KSM Kintsugi -> Karura❌
Extrinsic: https://kintsugi.subscan.io/extrinsic/1177886-2

KSM Heiko -> Karura❌
Extrinsic: https://parallel-heiko.subscan.io/extrinsic/1590447-2

**Comment by stepanLav** [comment]
Karura -> Parallel Heiko

amount: 0.1
sent - 0.100155308000
received - 0.099985805090
fee_heiko - 0,00013986
fee_kusama - 0.00002964291

Extrinsic:
https://karura.subscan.io/extrinsic/2311131-2
Event on Kusama:
https://kusama.subscan.io/event?extrinsic=13657085-1&page=2
Event on Heiko:
https://parallel-heiko.subscan.io/extrinsic/1591519-1?event=1591519-4

**Comment by stepanLav** [comment]
Got overestimate with reserveFee = 38_620_000_000:

Karura -> Moonriver

amount: 0.1
sent - 0.100258480000
received - 0.100124837090
fee_moonriver - 0,000104000000
fee_kusama - 0.00002964291

Extrinsic:
https://karura.subscan.io/extrinsic/2315970-3
Event on Kusama:
https://kusama.subscan.io/event?extrinsic=13657085-1&page=2
Event on Moonriver:
https://moonriver.subscan.io/extrinsic/2244243-0?event=2244243-3

**Comment by stepanLav** [comment]
Task linked: [CU-2t7uby9 Add xTokensReserve for KSM in Moonriver, Karura, Kinstugi, Heiko](https://app.clickup.com/t/2t7uby9)

**Review by leohar — APPROVED** [review]

**Pull request merged**
